version: "3"

services:
  cerberus-example-app:
    build: .
    container_name: cerberus-example-app
    ports:
      - "8081:8081"

  cerberus-example-ui:
    build: ./web
    container_name: cerberus-example-ui
    ports:
      - "3001:3001"
    command: npm start
    volumes:
      - ./web/src:/app/src
      - ./web/public:/app/public
    environment:
      - WATCHPACK_POLLING=true
